### ISSUE TITLE
Error in Err function

### ISSUE THREAD

**Issue by ZoeTan** [vincent-dk/sglOptim#1]
Hi, Vincent
I want to get errors from cross validation, But when I run the following code, I will get error warning. I am not sure what is wrong. Please help me on this. Thanks very much

fit1a.cv <-sgl_cv("sgl_test_dense", "sglOptim", data, covariateGrouping, groupWeights, parameterWeights, alpha, lambda, fold = 10, cv.indices = list())

error=Err(fit1a.cv)

Error in UseMethod("Err") : 
  no applicable method for 'Err' applied to an object of class "sgl"

**Comment by ZoeTan** [comment]
is there anything wrong in my packages? How can I get the error calculation from the crossvalidation?

**Comment by vincent-dk** [comment]
Hi ZoeTan, in general you will need to implement a package specific Err function. You may use the compute_error helper function to do this. It may help to take a look at the implementation in the packages Xsgl, msgl, lsgl and logitsgl. Also note that I'm doing some refactoring of the package at the moment -- in order to facilitate more complex models needed by my work -- hence some minor changes may occur the following weeks.

**Comment by ZoeTan** [comment]
Hi, Martin

Thanks for your email.

I will do it according to your suggestions.

Thanks.

ZoeTan
